app/controllers/application_controller.rb, app/controllers/reservations_controller.rb, spec/controllers/application_controller_spec.rb
=> #1072 Cleanup Before Filter

app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/models/ability.rb, app/models/cart_validations.rb, app/views/cart_js/update_cart.js.erb, app/views/catalog/_catalog_listing.html.erb, app/views/catalog/_equipment_model_div.html.erb, app/views/reservations/_cart_dates.html.erb, app/views/reservations/_cart_sidebar.html.erb, config/routes.rb
Resolves #1060 and others (e.g. #718 and #997)
=> #1060 Cart Fixes

app/controllers/app_configs_controller.rb, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/contact_controller.rb, app/controllers/equipment_models_controller.rb, app/models/ability.rb, app/views/app_configs/_form.erb, db/migrate/20141219172429_add_enable_guests_to_app_configs.rb, db/schema.rb, spec/features/auth_spec.rb, spec/features/guest_spec.rb, spec/features/login_spec.rb, spec/support/capybara_form_helper.rb, spec/support/feature_helpers.rb
Resolves #175, currently includes some tests but still in progress (dependent on #1068)
=> #175 Guest Functionality

CHANGELOG.md
Resolves #1084; includes all v4.2.0 changes including #708 and #994. Please check for typos and broken / incorrect links.
=> #1084 v5.0.0 changelog

app/mailers/admin_mailer.rb, app/mailers/user_mailer.rb, spec/mailers/admin_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
=> #1064 overdue fine e-mail

app/controllers/catalog_controller.rb, app/models/cart.rb, app/models/cart_validations.rb, app/models/report.rb, app/models/reservation.rb, app/models/reservation_scopes.rb
removes duplication and complexity from the cart validation module
=> [1097] cart validation improvements

app/controllers/application_controller.rb
=> #1149 Fix date update flash

Gemfile, Gemfile.lock, app/views/reservations/_new_request.html.erb, app/views/reservations/_new_reservation.html.erb
Resolves #1110, should be fine
=> #1110 Remove dynamic_form

app/assets/stylesheets/equipment_models/_show.css.scss
=> changed calendar_cell to box-sizing: border-box

lib/equipment_import.rb
Resolves #1140, fixes current bugs pending rewrite in #899.
=> #1140 Equipment Import

app/assets/javascripts/calendar.js, app/assets/stylesheets/equipment_models/_show.css.scss
=> [1152] disable calendar clicks

app/views/reservations/show.html.erb
=> #1159 Equipment Item Link

Gemfile, Gemfile.lock
Final part of #600, removed an unused gem and added a comment to the Gemfile.
=> #600 clean gemfile

app/views/admin_mailer/overdue_checked_in_fine_admin.html.erb, app/views/reservations/_form.html.erb, app/views/user_mailer/checkin_receipt.html.erb, app/views/user_mailer/checkout_receipt.html.erb, app/views/user_mailer/overdue_checked_in_fine.html.erb, app/views/user_mailer/reservation_confirmation.text.erb, spec/mailers/user_mailer_spec.rb
Not sure if I did this right, '
Original Issue : https://github.com/YaleSTC/reservations/issues/1102
Added reservation link to late fee emails
=> 1102 markdown ify email

app/controllers/users_controller.rb, app/views/users/show.html.erb
=> #1028 Request Flag

CHANGELOG.md
=> #1155 v5.1.0 CHANGELOG

app/assets/stylesheets/equipment_models/_table.scss, app/models/equipment_model.rb, app/models/equipment_object.rb, app/views/categories/show.html.erb, app/views/equipment_models/_table.html.erb, app/views/equipment_models/index.html.erb, db/migrate/20150227032011_add_equipment_objects_count_to_equipment_models.rb, db/schema.rb, spec/models/equipment_model_spec.rb
Resolves #1009. The table below replaces the current table on the equipment models index and is added to the category show view.
=> 1009 equipment status in category

app/controllers/reservations_controller.rb, app/models/reservation.rb
=> [1139] fix broken checkout checkin procedures

app/helpers/application_helper.rb, app/views/layouts/_flash_alerts.html.erb
=> [1124] allow toggleable filtering of html in markdown

app/models/equipment_model.rb, config/environments/development.rb, config/initializers/rails_admin.rb
Resolves #1122 as well as removes the annoying 'mini profiler resources not found' error message in Rails Admin
=> [1122] rails admin

app/models/equipment_model.rb, app/views/equipment_models/show.html.erb
=> [1181] fix asset paths for documentation

app/controllers/application_controller.rb
=> [927] norecorderror

app/controllers/import_users_controller.rb, lib/csv_import.rb
=> [1094] importusers

app/controllers/application_controller.rb, app/views/catalog/_catalog_listing.html.erb, app/views/catalog/_equipment_model_div.html.erb, app/views/catalog/index.html.erb, app/views/catalog/search_results.html.erb
=> [980] refactor qualification view logic

Gemfile
Resolves #1165
- undid changes from Heroku implementation (#275)
(ignore the branch number, that was a typo)
=> [1165] Move seed script gems out of default group

app/controllers/equipment_models_controller.rb
Resolves #1016
- add method to EquipmentModelsController to fix filetype if necessary
=> [1016] Fix broken pdf upload on firefox

CONTRIBUTING.md
Resolves #1056, please check for typos but also make sure the content is good and makes sense. Thanks!
=> [1056] Contributing.md

app/views/cart_js/cart_dates_reload.js.erb, app/views/cart_js/reload_all.js.erb
Resolves #1213
- adds qualifications_hash parameter from #1207 to the following files:
- app/views/cart_js/cart_dates_reload.js.erb
- app/views/cart_js/reload_all.js.erb
=> [1213] Fix broken cart JS

app/controllers/equipment_models_controller.rb, app/models/reservation_scopes.rb, app/views/equipment_models/_pending_reservations_table.erb, app/views/equipment_models/show.html.erb, spec/controllers/equipment_models_controller_spec.rb, spec/features/eq_model_spec.rb
Resolves #987
- add table partial
- add future scope for reservations
- add integration tests
=> [987] Add pending reservations table to equipment model view

CHANGELOG.md
=> [1177] update CHANGELOG for v5.2.0

app/controllers/reservations_controller.rb, spec/controllers/reservations_controller_spec.rb
=> [1215] Send reservation checkout receipts on checkout

app/controllers/reservations_controller.rb, spec/controllers/reservations_controller_spec.rb
=> [1235] Empty cart redirects to the previous page

app/views/reservations/manage.html.erb
Resolves #1259. I accidentally got the branch prefix wrong :(
=> [1259] check box tag

app/views/rails_admin/main/force_delete.html.haml, config/initializers/rails_admin.rb, spec/features/rails_admin_spec.rb
Resolves #1062
- create custom Rails Admin action based on default delete action
=> [1062] Allow force deletion of resources from Rails Admin

app/controllers/users_controller.rb, app/helpers/users_helper.rb, spec/controllers/users_controller_spec.rb, spec/features/users_spec.rb
Resolves #1241
- add restriction in UsersController#ban
- remove ban button by modifying UsersHelper#make_ban_btn
- add specs
=> [1241] Prevent users from banning themselves

app/models/user.rb
=> [1253] Fix archiving reservations with missing reserver

lib/autocomplete.rb
Resolves #1237 
the fix was as simple as changing the quotation marks...
=> [1237] User autocomplete fixed for heroku/postgres

app/controllers/import_users_controller.rb, lib/csv_import.rb
=> [1271] Handle invaild unicode characters during CSV upload

app/controllers/reservations_controller.rb, spec/controllers/reservations_controller_spec.rb, spec/features/reservations_spec.rb
=> [1246] allow banned checkin

app/controllers/import_users_controller.rb, app/views/import_users/import.html.erb, lib/csv_import.rb, spec/controllers/import_users_controller_spec.rb, spec/fixtures/header_spaces_users.csv, spec/fixtures/invalid_utf8_users.csv, spec/fixtures/valid_users.csv, spec/spec_helper.rb
=> [1299] Clean Up #1271

db/seeds.rb
=> [1320] Fix CAS superuser created via seed script

config/initializers/authentication.rb, db/migrate/20150323013431_add_cas_login_to_users.rb
Resolves #1324 (and #1282 for real)
=> [1324] Actually fix authentication initializer

CHANGELOG.md
=> [1308] Update CHANGELOG for v5.4.0

lib/csv_import.rb
I did not run into the issue originally stated in #1272, but my import failed with a valid csv (according to the format we give) because the CAS login wasn't being set.
=> [1272] Bug with imported users table

app/models/ability.rb, app/views/equipment_models/_table.html.erb, spec/features/equipment_model_views_spec.rb, spec/support/feature_helpers.rb
=> [1199] Allow patrons to view a more informative equipment table

db/migrate/20141001000934_add_notes_to_equipment_objects.rb
Resolves #1330
* wrap entire migration in a transaction
* remove all references to models, write all queries / actions as raw SQL
=> [1330] Refactor EquipmentItem notes migration

app/views/catalog/search_results.html.erb
=> [1344] Fix partial with equipment item search results

config/initializers/secret_token.rb
=> [1356] Remove hard-coded secret_key_base

app/models/cart.rb
Resolves #1250 
Adds reserver's name to reservation note.
=> [1250] Changed reservation notes to include reserver

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Resolves #1354
- also added controller spec
=> [1354] Fix strong param issue with requirements

app/models/equipment_item.rb, spec/models/equipment_item_spec.rb
Resolves #296
- set uniqueness validator
- write model specs
=> [296] Ensure unique EquipmentItem serial given EquipmentModel

CHANGELOG.md
=> [1334] Update CHANGELOG for v5.5.0

CHANGELOG.md, app/assets/stylesheets/catalog/_index.css.scss, app/views/catalog/_equipment_model_div.html.erb
=> [1363] Fix overflowing availability number [v5.5]

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Resolves #1370 for v5.5.1-rc1
- Add controller spec for manual user creation with CAS
- Fix controller logic
=> [1370] Fix broken manual user creation with CAS [v5.5]

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Resolves #1370 on `master`
- Add controller spec for manual user creation with CAS
- Fix controller logic
=> [1370] Fix broken manual user creation with CAS [master]

db/migrate/20150405012126_remove_approval_status_from_reservation.rb
Resolves #1381 on `master`
- accounts for time zone issues with late check-in
- decouples migration from Reservation model
=> [1381] Refactor approval_status removal migration [master]

app/views/equipment_models/show.html.erb
=> [1379] Fixed Pending Reservations link on Equipment Model page [master]

app/views/equipment_models/show.html.erb
=> [1379] Fixed Pending Reservations link on Equipment Model page [v5.5]

.env.example, app/assets/javascripts/application.js, app/controllers/users_controller.rb, app/models/user.rb, config/secrets.yml.example
Resolves #1375 for v5.5
- accept new env variable with comma-separated parameters, and return concatenated results
=> [1375] Add affiliation handling to LDAP lookup [v5.5]

.env.example, app/assets/javascripts/application.js, app/controllers/users_controller.rb, app/models/user.rb, config/secrets.yml.example
Resolves #1375 for master
- accept new env variable with comma-separated parameters, and return concatenated results
=> [1375] Add affiliation handling to LDAP lookup [master]

app/views/equipment_models/_table.html.erb
=> [1380] Fix broken Total Stock count on Equipment Model table [v5.5]

app/views/equipment_models/_table.html.erb
=> [1380] Fix broken Total Stock count on Equipment Model table [master]

Capfile, config/deploy.rb, config/deploy/production.rb
Resolves #1373 on `release-v5.5`
- use built-in whenever tasks
=> [1373] Fix whenever / Capistrano integration [v5.5]

app/assets/stylesheets/catalog/_index.css.scss, app/views/catalog/_equipment_model_div.html.erb
=> [1363] Fix overflowing availability number [master]

app/views/users/_short_form.html.erb
=> [1376] Fix cancel button on quick new user modal [v5.5]

app/assets/stylesheets/_jquery_overrides.scss.erb
Gets rid of the unwanted height depicted in #1403
=> [1403] add override for search bar [master]

app/assets/stylesheets/_jquery_overrides.scss.erb
=> [1403] Fix navbar height [v5.5]

app/assets/stylesheets/app_configs/_edit.css.scss, app/assets/stylesheets/application.css.scss
=> [1266] Fix for ToS checkbox appearance on Admin->Settings

app/views/reservations/current_reservations.html.erb
Resolves #1414 for v5.5.1
- move future reservations above checked-out reservations
=> [1414] Reorder current reservations page [v5.5]

app/views/reservations/current_reservations.html.erb
Resolves #1414 on master
- move future reservations above checked-out reservations
=> [1414] Reorder current reservations page [master]

CHANGELOG.md
Resolves #1364 
Please review for typos / broken links.
=> [1364] Update CHANGELOG for v5.5.1

CHANGELOG.md, app/helpers/user_mailer_helper.rb, spec/helpers/user_mailer_helper_spec.rb
Resolves #1433 on release-v5.5
- add UserEmailHelper specs
=> [1433] Fix incorrect e-mail variable replacement [v5.5]

app/helpers/user_mailer_helper.rb, spec/helpers/user_mailer_helper_spec.rb
Resolves #1433 on master
- add UserEmailHelper specs
=> [1433] Fix incorrect e-mail variable replacement [master]

app/views/users/_short_form.html.erb
=> [1376] Fix cancel button on quick new user modal [master]

.env.example, app.json
Resolves #1419
- fixes in .env.example and app.json
Very simple, worth a double-check for typos though.
=> [1419] Update SERVE_STATIC to RAILS_SERVE_STATIC_FILES

lib/csv_import.rb, spec/controllers/import_users_controller_spec.rb, spec/fixtures/extra_columns_users.csv
=> [1439] User Import fails if there are extraneous columns in CSV [v5.5]

lib/csv_import.rb, spec/controllers/import_users_controller_spec.rb, spec/fixtures/extra_columns_users.csv
=> [1439] User Import fails if there are extraneous columns in CSV [master]

app/helpers/application_helper.rb, app/views/equipment_models/show.html.erb, spec/helpers/application_helper_spec.rb
Resolves #1425 on master
- add helper method in ApplicationHelper
- add specs for said helper method
=> [1425] Fix documentation links with relative url root [master]

app/controllers/reservations_controller.rb, app/views/layouts/_sidebar_with_search.html.erb, app/views/layouts/application_with_search_sidebar.html.erb
Resolves #1420 on v5.5
- inserts a user search onto the side of the results for the checkout/checkin receipt page
=> [1420] added search to receipt page [v5.5]

config/application.rb, config/environments/production.rb
=> [1465] Move URL helper config to application.rb [v5.5]

config/application.rb, config/environments/production.rb
=> [1465] Move URL helper config to application.rb [master]

app/controllers/reservations_controller.rb, app/views/layouts/_sidebar_with_search.html.erb, app/views/layouts/application_with_search_sidebar.html.erb
Resolves #1420 on master
- inserts a user search onto the side of the results for the checkout/checkin receipt page
=> [1420] added user search to checkin/checkout [master]

app/mailers/user_mailer.rb, app/models/reservation_scopes.rb, config/schedule.rb, spec/lib/tasks/email_checkin_reminder_rake_spec.rb, spec/mailers/user_mailer_spec.rb
=> [1446] Extra "Request Approved" e-mails sent nightly to missed reservations [v5.5]

CHANGELOG.md
=> [1431] v5.5.4 CHANGELOG [v5.5]

CHANGELOG.md, app/controllers/reports_controller.rb
Resolves #1476 for release-v5.5
Merging following a green build, we'll leave a proper review + specs for `master`
=> [1476] Fix bug with changing report dates [v5.5]

lib/csv_import.rb, spec/controllers/import_users_controller_spec.rb, spec/fixtures/cr_line_endings_users.csv
Resolves #1438
- Imported CSVs can now contain CR or CFLR line endings
=> [1438] User Import doesn't handle CR line endings [v5.5]

app/mailers/user_mailer.rb, app/models/reservation.rb, config/schedule.rb, spec/lib/tasks/email_checkin_reminder_rake_spec.rb, spec/mailers/user_mailer_spec.rb
=> [1446] Extra "Request Approved" e-mails sent nightly to missed reservations [master]

Gemfile
Resolves #1487
- realized that you can't use environment variables in the Gemfile
=> [1487] Fix CAS

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Resolves #1425 for real on `master`
=> [1425] Fix Paperclip URL helper (again) [master]

lib/tasks/setup_application.rake
=> [1491] Change the default missed reservation expiration time [master]

lib/tasks/setup_application.rake
Resolves #1491 on release-v5.5
=> [1491] Change the default missed reservation expiration time [v5.5]

config/locales/simple_form.en.yml
Resolves #1463 
Not sure if this is the appropriate fix, but if not I'm lost on this issue and don't think I'll be much use until I can work with somebody on it.
=> [1463] missing translation

app/models/cart_validations.rb, app/models/reservation.rb, app/queries/reservations/consecutive_with_query.rb, spec/models/cart_spec.rb
=> [1311] Check for consecutive reservations that bypass the length limit

db/schema.rb
Resolves #1517
- schema now has field limits, see issue for details
=> [1517] Add updated schema for Rails 4.2

app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/app_configs/_edit.css.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/equipment_models/_table.scss, app/views/equipment_models/show.html.erb
Fixes various UI issues
Resolves [#1492](https://github.com/YaleSTC/reservations/issues/1492) (on v5.5)
- Equipment model page displays correctly with unrestricted checkout lengths/renewal periods
- Rows of equipment item table are vertically centered
=> [1492] UI bugs [v5.5]

app/models/cart_validations.rb
Closes #1242
- change app/models/cart_validations.rb to tell
maximum number of available items, pluralizing properly
=> [1242] Clarify availability error messages

CHANGELOG.md
=> [1484] Update CHANGELOG for v5.5.6 [v5.5]

app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/equipment_models/_table.scss, app/views/equipment_models/show.html.erb
Closes #1492
- Change big-numbers mixin so font does not overflow table
- Adjust equipment_model show table columns to align better
- Add table_woo to CSS formatting to center rows vertically
- Left-align checkbox when resetting ToS
=> [1492] Fix UI issues

Capfile, config/deploy.rb, config/deploy/production.rb
Resolves #1373
- use built-in whenever tasks
=> [1373] Fix whenever / Capistrano integration [master]

config/schedule.rb
=> [1542] Remove Rails dependency from whenever.rb

CHANGELOG.md
Resolves #1362, please review for typos / missing issues / broken and/or incorrect links, thanks!
=> [1362] v6.0.0 changelog

Gemfile, Gemfile.lock, app.json
=> [1515] Change default Heroku e-mail addon to Sendgrid

spec/controllers/announcements_controller_spec.rb, spec/controllers/app_configs_controller_spec.rb, spec/controllers/blackouts_controller_spec.rb, spec/controllers/categories_controller_spec.rb, spec/controllers/contact_controller_spec.rb, spec/controllers/equipment_items_controller_spec.rb, spec/controllers/equipment_models_controller_spec.rb, spec/controllers/import_users_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/controllers/requirements_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/app_configs.rb, spec/features/guest_spec.rb, spec/features/reservations_archive_spec.rb, spec/features/reservations_spec.rb, spec/lib/csv_export_spec.rb, spec/lib/tasks/delete_missed_reservations_rake_spec.rb, spec/lib/tasks/delete_old_blackouts_rake_spec.rb, spec/lib/tasks/email_checkin_reminder_rake_spec.rb, spec/lib/tasks/email_checkout_reminder_rake_spec.rb, spec/lib/tasks/email_missed_reservations_rake_spec.rb, spec/lib/tasks/email_notes_to_admins_rake_spec.rb, spec/lib/tasks/email_overdue_reminder_rake_spec.rb, spec/lib/tasks/flag_rake_spec.rb, spec/mailers/admin_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/spec_helper.rb, spec/support/app_config_helpers.rb, spec/support/feature_helpers.rb
Resolves #1514. The suite passes when seeded with 18208, which used to fail.
=> [1514] Intermittent Failures

CHANGELOG.md
Resolves #1548, has already been reviewed by @esoterik so we'll be merging this following squash / rebase.
=> [1548] v6.1.0 changelog

spec/helpers/application_helper_spec.rb
Resolves #1528
- Mock relative root in application helper specs
=> [1528] Fix intermittent asset failure in specs

app/controllers/equipment_models_controller.rb, app/models/equipment_model.rb, spec/models/equipment_model_spec.rb, spec/models/reservation_spec.rb
=> [1600] Refactor Equipment Model Model Spec

.eslintrc.yml, .gitignore, .hound.yml, .rubocop.yml, .travis.yml, lib/tasks/style_checker.rake, package.json
=> [1581] Remove Hound, add ESLint

spec/controllers/equipment_models_controller_spec.rb, spec/support/controller_helpers.rb, spec/support/mockers/category_mock.rb, spec/support/mockers/equipment_item_mock.rb, spec/support/mockers/equipment_model_mock.rb, spec/support/mockers/mocker.rb, spec/support/mockers/reservation_mock.rb, spec/support/mockers/user_mock.rb, spec/support/shared_examples/controller_examples.rb
Resolves #1587 
We should probably discuss splitting large spec files like this one into smaller files
=> [1587] Refactor EquipmentModel controller spec

spec/controllers/equipment_items_controller_spec.rb, spec/support/controller_helpers.rb
Resolves #1588 
~~Not sure why, but stubbing `current_user` seems to not work, and some specs fail because of it.~~ Fixed!
=> [1588] Refactor EquipmentItems controller spec

spec/controllers/reservations_controller_spec.rb
Resolves 1586
One group of tests is still failing due to permissions
=> [1586] Refactor reservation controller spec

app/models/equipment_item.rb, spec/factories/equipment_items.rb, spec/models/equipment_item_spec.rb
Resolves #1610 
Travis will likely fail because rubocop won't like the reservation mocker because it's still checking for ruby 2.0
=> [1610] Refactor Equipment Item Model spec

Gemfile, Gemfile.lock, spec/models/equipment_model_spec.rb
Downgraded Permanent Record Gem
- downgraded Permanent Record Gem to 4.1.5 to resolve destroy issue
- Added a test to check that model destroy works
=> [1638] Downgraded Permanent Record Gem

spec/controllers/users_controller_spec.rb
=> [1595] Refactor users controller spec

app/models/cart_validations.rb, spec/models/cart_spec.rb
=> [1641] Fix cart validation reservation counting

spec/controllers/categories_controller_spec.rb
Resolves #1589 
Merge #1598 first!
=> [1589] Refactor category controller spec

app/controllers/reservations_controller.rb, app/mailers/user_mailer.rb, config/initializers/00_devise.rb, spec/controllers/contact_controller_spec.rb, spec/features/guest_spec.rb, spec/mailers/admin_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
Not ready for review yet; opening PR because it'll make working on this easier
=> [1584] Use AppConfig#check

app/views/equipment_models/show.html.erb
Resolves #1661
- moved items and procedures sections
=> Changed position of sections to match headers in navbar

app/models/user.rb, lib/ldap_helper.rb, spec/lib/ldap_helper_spec.rb
Resolves #1649
- Creates an empty spec file for the LDAPHelper class
=> [1649] Move LDAP into its own class

.env.example, .travis.yml, app/controllers/users_controller.rb, app/models/user.rb, app/views/import_users/import.html.erb, lib/csv_import.rb, lib/people_api_helper.rb, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb
Resolves #1648
- Replace User.search_ldap with User.search
- Add PeopleAPIHelper to handle API requests
=> [1648] Add People API search functionality (LDAP alternative)

CHANGELOG.md, app.json
=> [1680] Fix Heroku button by updating post-deploy script

CHANGELOG.md, app/controllers/application_controller.rb, app/controllers/reports_controller.rb, app/controllers/reservations_controller.rb, app/controllers/status_controller.rb, app/helpers/application_helper.rb, app/helpers/equipment_models_helper.rb, app/helpers/requirements_helper.rb, app/models/equipment_model.rb, app/models/requirement.rb, app/models/reservation.rb, app/queries/reservations/upcoming_query.rb, app/views/admin_mailer/overdue_checked_in_fine_admin.html.erb, app/views/equipment_models/_add_to_cart.html.erb, app/views/layouts/_flash_alerts.html.erb, app/views/reservations/_check_out_form.html.erb, app/views/reservations/review.html.erb, app/views/terms_of_service/_user_accepted.html.erb, app/views/user_mailer/_due_today.html.erb, app/views/user_mailer/_missed.html.erb, app/views/user_mailer/_overdue.html.erb, app/views/user_mailer/_starts_today.html.erb, config/application.rb, lib/class_from_string.rb, lib/searchable.rb, spec/helpers/equipment_model_helper_spec.rb, spec/helpers/requirements_helper_spec.rb, spec/lib/class_from_string_spec.rb, spec/models/equipment_model_spec.rb, spec/models/requirement_spec.rb
Resolves #1632, #1631, #1630, #1628
- Properly use protect_from_forgery
- Restrict dynamically-generated class names to only expected classes
- Fix CSRF vuln in StatusController
- Fix SQL injection vuln in reservation date scopes
- Fix XSS vulns
- Replace calls to #html_safe with #sanitize
- Document vulns reported by brakeman that no longer pose risks
=> Fix various security vulnerabilities

CHANGELOG.md, app/controllers/status_controller.rb, config/deploy.rb, db/migrate/20160304025530_add_overdue_count_to_equipment_models.rb, db/migrate/20160329015527_add_ordering.rb, db/migrate/20160610135455_add_requests_affect_availability_to_app_config.rb, db/schema.rb
Resolves #1676
- Version all post-Rails-5 migrations (since v6.0.0-beta)
- Fix some broken data update queries
=> [1676] Fix broken database migrations

CHANGELOG.md
We need to remember to squash and merge this before cutting a new version!
=> V630 changelog

CHANGELOG.md, db/migrate/20160311070200_add_autodeactivate_on_archive_to_app_config.rb
=> [1684] Add missing migration version identifier

app/controllers/application_controller.rb, app/views/equipment_models/show.html.erb
=> [1686] Fix broken references to helper method

config/application.rb
Resolves #1687, blocked on #1688
=> [1687] Fix eager class loading of lib/ files

.travis.yml, config/routes.rb, spec/controllers/app_configs_controller_spec.rb
=> [1691] Fix broken settings form / app config routes

CHANGELOG.md, app/controllers/blackouts_controller.rb
Resolves #1698
Blocked on #1697
=> [1698] Fix recurring blackout date creation

CHANGELOG.md, app/models/ability.rb, lib/seed/user_generator.rb
=> [1706] Fix user signup when guest access is disabled

CHANGELOG.md, app/helpers/reservations_helper.rb
=> [1711] Fix issue with rendering future reservations

CHANGELOG.md, app/controllers/reservations_controller.rb, app/helpers/equipment_models_helper.rb
Resolves #1713, blocked on #1712
- Also includes an eager loading fix for the manage reservations page
=> [1713] Fix issue with equipment item select input on checkout

CHANGELOG.md, app/controllers/blackouts_controller.rb, app/controllers/reservations_controller.rb, app/models/reservation.rb, app/queries/reservations/affected_by_blackout_query.rb, app/views/app_configs/edit.html.erb, app/views/layouts/_footer.html.erb, db/migrate/20180624231458_fix_overdue_count.rb, db/schema.rb, spec/features/blackout_spec.rb, spec/features/receipt_spec.rb, spec/features/task_buttons_spec.rb
Resolves #1644, #1717, #1722, #1723, and #1725 as well as any other bugs I find while messing around with this.
=> [1644] [1717] [1722] [1723] [1725] bug fixes

CHANGELOG.md, app/controllers/application_controller.rb, spec/features/catalog_requirements_spec.rb
=> Fixing 500 error caused by requirements

app/views/app_configs/edit.html.erb
=> Change app_configs helper path to relative instead of absolute

CHANGELOG.md, app/jobs/application_job.rb, app/jobs/daily_tasks_job.rb, app/jobs/hourly_tasks_job.rb, spec/jobs/daily_tasks_job_spec.rb, spec/jobs/hourly_tasks_job_spec.rb
=> Change rake task to execute immediately instead of enqueing

CHANGELOG.md, app/helpers/reservations_helper.rb, app/views/reservations/show.html.erb, spec/helpers/reservations_helper_spec.rb
Resolves #1747
Fixes an issue where the helper method always returned a "Review
Request" button even for approved requests. Also added specs for the
helper method :-D.
=> [1747] Fix issue with the manage reservation button for requests

CHANGELOG.md, app/views/equipment_models/show.html.erb, spec/features/eq_model_spec.rb
=> [1749] Fix unauthorized display of sensitive equipment model info

CHANGELOG.md, config/environments/production.rb
=> [1743] Rotate log files after 150 MB (retain 5)

CHANGELOG.md, app/models/reservation.rb, spec/models/reservation_spec.rb
=> [1754] Fix counter cache when destroying overdue reservations

CHANGELOG.md, app/controllers/application_controller.rb, spec/features/flash_spec.rb
=> [1760] Fixing broken links in flash messages

CHANGELOG.md, app/models/blackout.rb, app/queries/reservations/affected_by_recurring_blackout_query.rb, app/views/blackouts/_form.html.erb, app/views/blackouts/new.html.erb, spec/features/blackout_spec.rb, spec/queries/reservations/affected_by_recurring_blackout_query.rb
=> [1756] Fixing recurring blackout overlap query

Gemfile.lock
=> [1767] Update rack from 2.0.5 -> 2.0.6

CHANGELOG.md, app/views/import_users/_import_table.html.erb, lib/csv_import.rb, spec/features/import_users_spec.rb, spec/fixtures/users_to_ban.csv, spec/lib/csv_import_spec.rb
=> [1765] Fixing user CSV importer bug

CHANGELOG.md, app/views/blackouts/edit.html.erb, lib/blackout_updater.rb, spec/features/blackout_spec.rb, spec/lib/blackout_updater_spec.rb, spec/spec_helper.rb
Resolves #1771
Blocked on #1776
=> [1771] Fix issue with editing blackouts
