.jscsrc, .jshintignore, .jshintrc, .travis.yml
Adds and configures the linters [jscs](https://www.npmjs.com/package/jscs) and [jshint](http://jshint.com/). Merging into @orenyk's branch since that seems to make the most sense right now.
Also streamlines `bundle install` since we're now just installing what we need to run tests instead of everything.
NOTE: The Travis build *should* be failing, because both jscs and jshint are failing.
=> [1075] Add jscs and jshint

db/default_messages/deleted_missed_email, db/default_messages/overdue_email, db/default_messages/tos_text, db/default_messages/upcoming_checkin_email, db/seeds.rb
Resolves #1071. Also includes a load of refactorizations and other improvements, as well as #629 
* Use `prompt_field` method to prompt for value, assign/save and validate
* Define a method to build a model instance and pass its name to new `generate_objs` method.
* Abstract out some stuff into global vars
* New modes for the script: `semi`, which only autogenerates the superuser and appconfigs but prompts for other data, `no_pics` which doesn't assign images to equipment models (makes the script way faster), and `fast` which invokes `no_pics` and `minimal`. For comparison, on my machine `minimal` runs in 26 seconds and `fast` runs in 6.
* Seed script now draws from the whole database instead of the items created in the current instance of the script. Before even if your database had 1000 …
=> 1071 seed script

db/seeds.rb
=> #1071 carnage fixes [1088]

lib/tasks/delete_missed_reservations.rake, spec/controllers/app_configs_controller_spec.rb, spec/lib/tasks/delete_missed_reservations_rake_spec.rb
Resolves #1059, currently not doing the trick :-\
=> #1059 Intermittent Tests

app/controllers/application_controller.rb, app/models/cart.rb, spec/models/cart_spec.rb
=> #1085 Non-existent cart items

app/assets/javascripts/calendar.js, app/controllers/equipment_models_controller.rb, app/controllers/requirements_controller.rb, app/models/requirement.rb, app/views/catalog/_equipment_model_div.html.erb, app/views/equipment_models/_add_to_cart.html.erb, app/views/equipment_models/show.html.erb, spec/models/requirement_spec.rb
resolves #1053 and adds a couple other things
* when item is deactivated, 'add to cart' button is red and says 'deactivated' to show status of item
* when item is restricted, 'add to cart' button is yellow and says 'not qualified', when clicked the qualification modal comes up
* calendar cells are always red if no items are available. an edge case (0 items in existence, or model is deactivated) would cause them to be green
* fixes bug with requirement strong parameters not working
* adds requirement description to the modal dropdown
=> 1053 decativated status

.env, .env.example, .gitignore, Gemfile, Gemfile.lock, Procfile, README.md, app.json, app/models/ability.rb, bin/bundle, bin/rails, bin/rake, config/environment.rb, config/environments/production.rb, config/environments/staging.rb, config/initializers/timeout.rb.example, config/schedule.rb, config/unicorn.rb, lib/tasks/delete_old_blackouts.rake, lib/tasks/scheduler.rake
Resolves #275 (and #1104)~~, needs to be squashed but appears to be fully functional :-).~~
~~Things I have not yet tested:~~
* ~~LDAP~~
* ~~CAS~~
=> #275 Heroku

CHANGELOG.md, app/controllers/reservations_controller.rb, app/controllers/users_controller.rb, app/models/cart_validations.rb, app/models/reservation.rb, app/models/reservation_validations.rb
Resolves #1185 on `release-v3.4`
- add cart validation for banned reservers
- add reservation validation for banned reservers on create
- add flash message when viewing banned user profile
- prevent viewing of manage / current view for banned users
- prevent checkout of equipment to banned users
=> [v3.4] #1185 Fix Banned Users

Gemfile, app/controllers/reservations_controller.rb, app/controllers/users_controller.rb, app/models/cart_validations.rb, app/models/reservation.rb, app/models/reservation_validations.rb, spec/controllers/application_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/reservation_spec.rb
=> [1185] Fix Banned Users

app/controllers/application_controller.rb, app/controllers/reservations_controller.rb, app/controllers/users_controller.rb, app/mailers/admin_mailer.rb, app/mailers/notifications_mailer.rb, app/mailers/user_mailer.rb, app/models/ability.rb, app/models/app_config.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, app/views/reservations/_index_nav.html.erb, app/views/users/_form.html.erb
Resolves #1144 as well as introduces some syntactic sugar to avoid this type of error in the future: when accessing/testing appconfig values use `AppConfig.check(:property)` instead of `AppConfig.first.property`
=> [1144] navbar preapp

app/views/equipment_items/_form.html.erb, app/views/equipment_items/edit.html.erb, app/views/equipment_items/new.html.erb, app/views/equipment_items/show.html.erb, app/views/equipment_models/_table.html.erb, app/views/layouts/_navbar.html.erb, config/routes.rb
=> [1082] remove the equipment item index page

app/models/user.rb, config/initializers/00_devise.rb, db/migrate/20150327012721_add_rememberable_to_users.rb, db/schema.rb
Resolves #1109
- add devise :rememberable module
- update devise.rb initializer
- add remember_created_at column to users table
=> [1109] Add rememberable option for password authentication

app/controllers/equipment_models_controller.rb, app/controllers/import_equipment_controller.rb, app/views/equipment_models/_table.html.erb, app/views/import_equipment/imported.html.erb
resolves #1192
- refactor `@equipment_models` setting in `EquipmentModelsController#index`
- move eager loading from partial to controller
=> [1192] Equipment model import broken

CHANGELOG.md, app/controllers/reservations_controller.rb
Resolves #1227 for v3.4.9
Based on change for the `master` branch (`1227_tos_bug`) but that PR is pending the merging of #1219.
=> [1227] [v3.4] Fix broken ToS checkbox handling

app/assets/stylesheets/reservations/_cart_sidebar.css.scss, app/controllers/catalog_controller.rb, app/models/cart.rb, app/views/reservations/_list_items_in_cart.html.erb, config/routes.rb, spec/controllers/catalog_controller_spec.rb, spec/features/guest_spec.rb, spec/models/cart_spec.rb
=> [1114] change item quantities in cart

CHANGELOG.md, app/controllers/reservations_controller.rb
Resolves #1227 on `release-v5.2`
Should be a quick merge based on #1228, but for consistency let's get this looked over.
=> [1227] [v5.2] Fix broken ToS checkbox handling

app/assets/javascripts/calendar.js
Resolves #1218
- use `dateInTimeZone` instead of `new Date` for consistency
=> [1218] Fix broken calendar JS

app/assets/javascripts/manage_reservation.js, app/controllers/application_controller.rb, app/controllers/reservations_controller.rb, spec/controllers/reservations_controller_spec.rb, spec/features/reservations_spec.rb
Resolves #1227 on `master`
- add integration specs for ToS checkbox
- fix banned user view handling
- remove check_tos method and only update user if checkout succeeds
- tweak JS confirmation message on manage reservation page
=> [1227] Fix broken ToS checkbox handling

app/models/reservation.rb, spec/models/reservation_spec.rb
Resolves #1267
- Reservation#approved? method correctly handles open requests
- add specs for Reservation#approved?
=> [1267] Fix Reservation#approved? method

app/views/equipment_items/show.html.erb
=> [1245] Restrict equipment item note viewing to admins and higher

app/controllers/reservations_controller.rb, app/models/reservation.rb, app/views/admin_mailer/overdue_checked_in_fine_admin.html.erb, app/views/reservations/_check_in_form.html.erb, app/views/reservations/_check_out_form.html.erb, app/views/reservations/_index_nav.html.erb, app/views/reservations/_reservations_list.html.erb, app/views/user_mailer/_returned_overdue.html.erb
Resolves #1121. Allows viewing of returned overdue reservations in the reservations index tabs.
=> [1121] view returned overdue

app/assets/stylesheets/autocomplete.scss
Resolves #1251 by using bootstrap blue for highlighting as well as changing the pointer cursor for additional visual cue. Also removes some old css that wasn't doing anything
=> [1251] autocomplete ux

app/controllers/reservations_controller.rb, app/mailers/admin_mailer.rb, app/mailers/user_mailer.rb, app/views/app_configs/_form.erb, app/views/user_mailer/_due_today.html.erb, app/views/user_mailer/_missed.html.erb, app/views/user_mailer/_overdue.html.erb, app/views/user_mailer/_starts_today.html.erb, db/default_messages/deleted_missed_email, db/default_messages/overdue_email, db/default_messages/upcoming_checkin_email, db/default_messages/upcoming_checkout_email, lib/tasks/setup_application.rake, spec/mailers/admin_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
Resolves #1240 
I'm not 100% sure that I handled the admin reply-to / from issue in the best way (and it was a bit difficult to test), but I'm pretty sure this works.
=> [1240] email issues

config/initializers/authentication.rb
Resolves #1282
- automaticaly skip initializer unless `User.respond_to?(:username)`
=> [1282] Skip auth initializer if using a pre-v4.1.0 DB

app/controllers/app_configs_controller.rb, app/mailers/admin_mailer.rb, app/models/cart.rb, app/views/admin_mailer/reservation_created_admin.html.erb, app/views/app_configs/_form.erb, db/migrate/20150719040438_add_notify_admin_on_create_to_app_config.rb, db/schema.rb, db/seeds.rb, lib/tasks/setup_application.rake, spec/controllers/reservations_controller_spec.rb, spec/factories/app_configs.rb, spec/mailers/admin_mailer_spec.rb
Resolves #1284
- add `notify_admin_on_create` parameter to app configs
(default false)
- add `reservation_created_admin` method to AdminMailer
- update e-mail sending logic in Cart
- reordered the app config form a bit
- add tests for all the things
=> [1284] Add optional admin email on Reservation creation

lib/tasks/flag_overdue.rake, spec/lib/tasks/flag_rake_spec.rb
Resolves #1274
- ensures that missed rake tasks don't leave orphaned reservations
- add spec
=> [1274] Extend query in flag_overdue past yesterday

app/controllers/reservations_controller.rb, app/models/reservation.rb, spec/controllers/reservations_controller_spec.rb, spec/features/reservations_spec.rb, spec/support/feature_helpers.rb
Resolves #1243
- remove `EquipmentItem#make_reservation_notes` calls from `Reservation`
methods
- only add equipment item notes once the relevant reservation has been
saved to the database
- add specs for failed checkout / checkin to ensure that equipment item
notes aren't saved
- improve `current_user` feature spec helper method
- fix N+1 query in the manage reservations view
- add exception handling to `ReservationsController#archive`
=> [1243] Add equipment item notes only after reservations save

app/controllers/app_configs_controller.rb, app/mailers/user_mailer.rb, app/views/app_configs/_form.erb, db/migrate/20150719050013_add_disable_user_emails_to_app_configs.rb, db/schema.rb, spec/mailers/user_mailer_spec.rb
Resolves #1286
- add `disable_user_emails` to app configs
- cause `reservation_status_update` to return if set
- add spec
=> [1286] Add kill switch for user e-mails

app/controllers/equipment_models_controller.rb, app/models/reservation.rb, app/views/equipment_models/_form.html.erb, db/migrate/20150719052612_add_late_fee_max_to_equipment_models.rb, db/schema.rb, spec/models/reservation_spec.rb
Resolves #1285
- add `late_fee_max` parameter to Equipment Models
- update `Reservation#late_fee` logic to account for it
- add specs for `Reservation#late_fee`
- make `Reservation#late_fee` return 0 if reservation isn't overdue
=> [1285] Add optional cap to reservation late fee

app/mailers/user_mailer.rb, app/models/reservation.rb, app/views/user_mailer/_request_expired.html.erb, lib/tasks/deny_missed_requests.rake, spec/lib/tasks/flag_rake_spec.rb, spec/mailers/user_mailer_spec.rb
Resolves #1203
- Adds new reservation email type 'request expired'
- deny_missed_requests sends notification emails
- Adds a new flag 'expired'
- Spec for deny_missed_requests updated
- Spec for 'request expired' emails
=> [1203] Add request expired notifications

.env.example, config/initializers/setup_mail.rb, spec/mailers/user_mailer_spec.rb
Resolves #1127 
this shouldn't be merged until #1203 is merged
=> [1127] Add an ENV variable to log rake emails

db/seeds.rb, lib/tasks/setup_application.rake
Resolves #1265
This also makes the same script in db/seeds.rb (prompt_password) not show the typed password too.
=> [1265] Setup script for setting up initial user doesn't echo the typed password

Gemfile, app.json, config/application.rb
Resolves #1345
- fix issue with missing logs
- add extra Gemfile group to app.json
- update Bundler call in application.rb
=> [1345] Move Heroku deployment gems into separate heroku group

app/assets/stylesheets/reservations/_index.css.scss, app/views/reservations/_reservations_list.html.erb
=> [724] Set minimum height for Reservations table

app/controllers/reservations_controller.rb, app/views/reservations/_index_nav.html.erb, spec/controllers/reservations_controller_spec.rb, spec/factories/reservations.rb
Resolves #1383 on master
- Add 'archived' tab and filter to the Reservations index
- ~~Display archived Reservations in the 'Past' category on the User profile page~~
- Add archived trait to the Reservations factory
- Update Reservations controller spec with new filter
=> [1383] Make archived reservations accessible [master]

app/controllers/reservations_controller.rb, app/views/reservations/_index_nav.html.erb, spec/controllers/reservations_controller_spec.rb, spec/factories/reservations.rb
Resolves #1383 on v5.5
- Add 'archived' tab and filter to the Reservations index
- ~~Display archived Reservations in the 'Past' category on the User profile page~~
- Add archived trait to the Reservations factory
- Update Reservations controller spec with new filter
=> [1383] Make archived reservations accessible [v5.5]

db/migrate/20150405012126_remove_approval_status_from_reservation.rb
Resolves #1381 for v5.5.1
- accounts for time zone issues with late check-in
- decouples migration from Reservation model
=> [1381] Refactor approval_status removal migration [v5.5]

app/models/ability.rb, spec/controllers/announcements_controller_spec.rb
=> [1339] hide announcement

app/models/ability.rb, spec/controllers/announcements_controller_spec.rb
Resolves #1339 for v5.5
- Change the ability file
- Add a cookie testing spec
- Add shared examples for specs
Reviewed in #1350, merging immediately.
=> [1339] Adding the ability to hide the announcements for all users [v5.5]

app/models/ability.rb
=> [1391] Refactor ability.rb

CHANGELOG.md, config/environments/production.rb
Resolves #1426 on release-v5.5
- correctly set default_url_options with relative root
=> [1426] Fix invalid AdminMailer from address [v5.5]

config/environments/production.rb
Resolves #1426 on master
- correctly set default_url_options with relative root
=> [1426] Fix invalid AdminMailer from address [master]

.env.example
Resolves #1427 
I'm merging this in without review as it's not really code.
=> [1427] Fix typo in .env.example

CHANGELOG.md, app/models/reservation_scopes.rb
Resolves #1449 for release-v5.5
- ensures that checked-out reservations are also taken into account
=> [1449] Fix cart availability validation [v5.5]

config/environments/production.rb
Resolves #1424 on release-v5.5
- extra after_initialize block in config/production.rb to pull settings from action_mailer
=> [1424] Properly configure url helpers to use relative root [v5.5]

config/environments/production.rb
Resolves #1424 on master
- extra after_initialize block in config/production.rb to pull settings from action_mailer
=> [1424] Properly configure url helpers to use relative root [master]

app/helpers/application_helper.rb, app/views/equipment_models/show.html.erb, spec/helpers/application_helper_spec.rb
Resolves #1425 on release-v5.5
- add helper method in ApplicationHelper
- add specs for said helper method
=> [1425] Fix documentation links with relative url root [v5.5]

CHANGELOG.md, app/controllers/users_controller.rb
Resolves #1471, resolves #1469 on `release-v5.5`
- controller takes CAS into account
- cart reserver is now set as the new user after creation
Will be merged following a green build, the PR for `master` will be left open for review.
=> [1471] Fix quick new user modal with CAS [v5.5]

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Resolves #1425 again on release-v5.5; merging after green build, will leave a PR open on `master` for proper review (this has been tested on DEV)
=> [1425] Fix Paperclip URL helper (again) [v5.5]

CHANGELOG.md, Gemfile, Gemfile.lock, app/models/reservation.rb, spec/features/reservations_spec.rb, spec/lib/tasks/flag_rake_spec.rb
Resolves #1479 on release-v5.5
- add `before_save` callback to reservation model to update the `overdue` flag for checked out reservations to match the due date
- add note to `Reservation#update` when toggling the overdue parameter
- update Rails Admin to v0.8.1 to allow editing of reservations
Merging following a green build so we can deploy this in the morning - verified manually on local instance. PR for master will include specs and be properly reviewed.
=> [1479] Fix issue with editing overdue reservations [v5.5]

app/controllers/equipment_models_controller.rb, app/decorators/category_decorator.rb, app/decorators/equipment_model_decorator.rb, app/models/cart_validations.rb, app/models/equipment_model.rb, app/models/reservation.rb, app/queries/reservations/overlaps_with_date_range_query.rb, spec/models/cart_spec.rb, spec/models/reservation_spec.rb
Resolves #1449 on master
- replace `reserved_in_date_range` with `overlaps_with_date_range` that doesn't take status into account and add `active` where necessary
- add specs for cart availability validation
- fix specs for reservation availability validation
=> [1449] Fix cart availability validation [master]

lib/csv_import.rb, spec/controllers/import_users_controller_spec.rb, spec/fixtures/cr_line_endings_users.csv
Resolves #1438
- Imported CSVs can now contain CR or CFLR line endings
=> [1438] CSV Import Handles CR Line Endings [master]

Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/controllers/equipment_models_controller.rb, app/controllers/users_controller.rb, app/views/categories/index.html.erb, app/views/equipment_items/index.html.erb, app/views/equipment_models/index.html.erb, app/views/users/index.html.erb, lib/csv_export.rb, spec/lib/csv_export_spec.rb
Resolves #1337
- adds the module CsvExport to handle exporting CSV files
- also supports exporting multiple CSVs at once in a zip file
=> [1337] Add user and equipment CSV export

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Resolves #1471, resolves #1469
- controller takes CAS into account
- cart reserver is now set as the new user after creation
=> [1471] Fix quick new user modal with CAS [master]

app/controllers/reports_controller.rb, spec/controllers/reports_controller_spec.rb
Resolves #1476 on master
- add controller specs for this request
- add handling for missing params
- fix original issue (missing semicolon)
=> [1476] Fix bug with changing report dates [master]

app/models/reservation.rb, app/models/reservation_validations.rb, lib/tasks/flag_overdue.rake, spec/features/reservations_spec.rb, spec/lib/tasks/flag_rake_spec.rb, spec/models/reservation_spec.rb
Resolves #1479 on master with specs!
- add before_save callback to reservation model to update the
overdue flag for checked out reservations to match the due date
- add note to Reservation#update when toggling the overdue parameter
- update Rails Admin to v0.8.1 to allow editing of reservations
- updated broken specs
- added new specs for this behavior
=> [1479] Fix issue with editing overdue reservations [master]

app/controllers/blackouts_controller.rb
Resolves #1489 on release-v5.5
- use reserved_in_date_range instead of ends_on_date
Note that this was only tested manually; test coverage will be added on master.
=> [1489] Fix incorrect blackout conflict handling [v5.5]

app/controllers/blackouts_controller.rb, app/models/reservation.rb, app/queries/reservations/ends_on_days_query.rb, spec/controllers/blackouts_controller_spec.rb, spec/factories/reservations.rb
Resolves #1489 on master
- use `overlaps_with_date_range` instead of `ends_on_days`
- add controller specs for different statuses as well as start and due date checking
- remove useless `ends_on_days` scope / query object
- add `:archived_reservation` factory
=> [1489] Fix incorrect blackout conflict handling [master]

app/assets/javascripts/cart_pause-resume.js, app/assets/stylesheets/reservations/_new.css.scss, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/models/ability.rb, app/views/cart_js/reservation_form.js.erb, app/views/reservations/_cart_dates.html.erb, app/views/reservations/_edit_reservation_form.html.erb, app/views/reservations/_new_request.html.erb, app/views/reservations/_new_reservation.html.erb, app/views/reservations/new.html.erb, config/routes.rb, spec/controllers/application_controller_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/features/reservations_spec.rb, spec/support/feature_helpers.rb
Resolves #237
- Redesign & Add form to confirm reservation page
- Allow user to edit cart & dates on confirm reservation page
- Lock cart when changing quantities
- Add submit_cart_updates_form in catalog controller to update cart with changes on confirm reservation page & redirect
- Add change_reservation_dates in catalog controller to update cart dates
- Separate update_cart in application controller into two different methods: performing cart updates and appropriate redirections/js calls
- Add reservation_form.js to dynamically switch between reservations and reservation requests
- Add controller tests & feature tests
(edited to reflect full changes)
=> [237] change cart reservation

app/controllers/reservations_controller.rb, spec/features/reservations_spec.rb
Resolves 1502.
Redirects to root_path if request.env['HTTP_REFERER'] is not present.
Added tests to verify this behavior
=> [1502] direct reservation back error [v5.5]

app/controllers/reservations_controller.rb, spec/features/reservations_spec.rb
closes #1502
- edit reservation_controller new code to redirect to root if
HTTP_REFERER not present
- add appropriate tests to spec/features/reservations_spec.rb
=> [1502] Redirect correctly  on invalid reservation/new request

app/controllers/users_controller.rb, app/views/terms_of_service/_user_accepted.html.erb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, spec/features/profile_spec.rb
Fixes ToS checkbox logic
Resolves #1497 (on v 5.5)
- Enables ToS checkbox for self-created users
- Disables ToS checkbox for all users(admins) modifying other users
- Now clarifies Editing Profile vs Editing User on Edit Page (and alters relevant tests)
=> [1497] Fixes ToS checkbox logic [v5.5]

app/controllers/users_controller.rb, app/views/terms_of_service/_user_accepted.html.erb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, spec/features/profile_spec.rb
Resolves #1497 
- Enables ToS checkbox for self-created users
- Disables ToS checkbox for all users(admins) modifying other users
- Now clarifies Editing Profile vs Editing User on Edit Page
- Edits tests to match
=> [1497] Fixes ToS checkbox logic [master]

app/mailers/notifications_mailer.rb, app/models/app_config.rb, db/seeds.rb, lib/tasks/setup_application.rake, spec/controllers/contact_controller_spec.rb, spec/factories/app_configs.rb, spec/models/app_config_spec.rb
Resolves #1524 on `master`
- add `AppConfig.contact_email` to correctly default to admin e-mail when no contact e-mail is set
- add validations for `AppConfig.contact_link_location` to ensure it is a valid e-mail if it's not blank
- update seed and application setup script to assign valid e-mails to `contact_link_location` by default, as well as update factories
- add specs
=> [1524] Resolve issues with contact form [master]

app/controllers/app_configs_controller.rb, app/controllers/equipment_items_controller.rb, app/controllers/reservations_controller.rb, app/models/equipment_item.rb, app/views/app_configs/_form.erb, db/migrate/20160311070200_add_autodeactivate_on_archive_to_app_config.rb, db/schema.rb, spec/controllers/equipment_items_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/features/reservations_archive_spec.rb, spec/models/equipment_item_spec.rb, spec/support/feature_helpers.rb
Resolves #1384
- add `autodeactivate_on_archive` parameter to `AppConfig`
- move equipment item deactivation to a model method
- tweak `ReservationsController#archive` method to implement auto-deactivation
- add feature specs for reservation archiving
- add model specs for `EquipmentItem#deactivate`
- add controller specs for `ReservationsController#archive` with auto-deactivation
- `FeatureHelpers#app_setup` now deletes any pre-existing `AppConfigs`
=> [1384] Add optional archival deactivation of equipment

lib/searchable.rb, spec/controllers/catalog_controller_spec.rb
Resolves #933
- Makes search results unique by flattening results array before unique is called
- Tests for duplicate items in search results
=> [933] Makes search results unique

app/controllers/catalog_controller.rb, app/controllers/reservations_controller.rb, app/helpers/reservations_helper.rb, app/views/reservations/_new_request.html.erb, spec/factories/app_configs.rb, spec/features/reservations_spec.rb
Resolves #1544
- moves request text assignment code to `ReservationsHelper`
- manually include `ReservationsHelper` in `CatalogController`
In principle I'd like to move the reservation/cart update methods from `CatalogController` to `ReservationsController` (since they're ultimately being called from the `ReservationsController#new` page), which would preclude the need to manually include `ReservationsHelper` in `CatalogController` - can someone chime in and let me know if they think it's worth doing?
=> [1544] Request text is now shown after invalid cart edit

app/views/reservations/show.html.erb
Resolves #1532
Quick fix to remove `<p>` wrapper around `h4` tags defining START DATE, DUE DATE pairs and actual date pairs.
=> [1532] res show date align

app/controllers/categories_controller.rb, app/controllers/equipment_items_controller.rb, app/controllers/equipment_models_controller.rb, app/views/categories/index.html.erb, app/views/categories/show.html.erb, app/views/equipment_items/index.html.erb, app/views/equipment_models/index.html.erb, config/routes.rb, lib/csv_export.rb
=> [1499] Clean up #1337

app/controllers/application_controller.rb, app/controllers/equipment_models_controller.rb, app/decorators/equipment_item_decorator.rb, app/models/cart.rb, app/models/cart_validations.rb, app/models/equipment_model.rb, app/models/reservation.rb, app/queries/reservations/reserved_on_date_query.rb, app/views/equipment_models/_table.html.erb, config/initializers/factory_girl.rb, db/migrate/20160304025530_add_overdue_count_to_equipment_models.rb, db/schema.rb, spec/controllers/equipment_models_controller_spec.rb, spec/factories/reservations.rb, spec/models/cart_spec.rb, spec/models/equipment_model_spec.rb, spec/models/reservation_spec.rb
Resolves #1501 
This is not finished yet, but it would be great if someone could look over the counter cache implementation and the changes to the reservation and equipment model models!
=> [1501] Availability Overhaul

db/seeds.rb
Resolves #1229, and incidentally #1263 as well.
Note that this is kind of a "band-aid" fix; the script still generates bad dates, but it doesn't save them, instead trying to build the reservation again (which it can do up to 50 times). #474 involves an overhaul of seed script functionality anyway, so I'm okay with this quick fix for now. I'm planning on working on #1327 and then #474 next.
=> [1229] Seed script generates reservations with start date after due date 

.hound.yml
Resolves #1577 
I don't think we need to do anything other than setting the rubocop config for now? I'll enable ESLint in #1572.
=> [1577] Configure Hound CI

app/controllers/app_configs_controller.rb, app/models/equipment_model.rb, app/views/app_configs/_form.erb, db/migrate/20160610135455_add_requests_affect_availability_to_app_config.rb, db/schema.rb, spec/controllers/equipment_models_controller_spec.rb, spec/models/equipment_model_spec.rb
Resolves #1521 
The `.gitignore` and `.rubocop.yml` updates are there because I have react-related files in my working directory and they aren't ignored on master yet.
=> [1521] Add global option to include requests in availability calculations 

app/models/user.rb
Resolves #1633
- fixed the regex string to look for only numbers and ()
=> Fix phone regex parsing

spec/spec_helper.rb
Resolves #1411
The `UsersController` test failure is fixed in #1595 by stubbing `User.search_ldap`. 
Importing users with LDAP is currently untested, so defaulting `USE_LDAP` to `nil` allows those tests to run even if the variable is set in `.env`. Setting this default would be a lot nicer if #1422 was merged, because we could have a `.env.test` file with `USE_LDAP=0` rather than deleting `USE_LDAP` from the `ENV` hash before running the test suite (my current solution). 
I don't think there are any other tests that hit LDAP; the model method isn't tested.
=> [1411] Running tests with USE_LDAP enabled outside of Yale breaks things

Rakefile, app/assets/javascripts/application.js, app/controllers/equipment_models_controller.rb, app/helpers/equipment_models_helper.rb, app/models/category.rb, app/models/equipment_model.rb, app/views/catalog/_catalog_listing.html.erb, app/views/equipment_models/_table.html.erb, app/views/layouts/_content_with_sidebar.html.erb, config.ru, config/routes.rb, db/migrate/20160329015527_add_ordering.rb, db/schema.rb, lib/ordering_helper.rb, lib/seed/equipment_model_generator.rb, lib/tasks/style_checker.rake, spec/controllers/equipment_models_controller_spec.rb, spec/factories/equipment_models.rb, spec/features/equipment_model_ordering_spec.rb, spec/features/equipment_model_views_spec.rb, spec/lib/ordering_helper_spec.rb, spec/models/equipment_model_spec.rb, spec/support/feature_helpers.rb
closes #1413 
- migrate to add ordering attribute and populate existing models
- update equipment_model creation to add ordering automatically
- add cell to /views/equipment_model/_table to show ordering
- add buttons to above table to adjust ordering
- add 'up' and 'down' routes to equipment_models_controller to adjust ordering
- create rspec testing
=> [1413] Add ordering attribute to models for display sorting

db/migrate/20160329015527_add_ordering.rb, lib/seed/equipment_model_generator.rb, lib/seed/reservation_generator_helper.rb, spec/factories/equipment_models.rb, spec/lib/generator_spec.rb
Resolves #1662
- set ordering to number of existing models in equipment_model generation
- add validations for generating multiple objects
- resolves error that can occur when randomly generating reservations for
equipment_model with max_checkout_length = 1
=> Repair equipment_model generator to handle ordering

CHANGELOG.md, Gemfile, Gemfile.lock, README.md, app.json
Resolves #1690
- Remove pg gem from Gemfile
- Add cleardb:ignite add-on
- Add DATABASE_URL ENV variable
- Update Travis script to install Ghostscript (due to update in Ubuntu
distro being used)
=> [1690] Fix Heroku deployment again (switch to MySQL)

CHANGELOG.md, app/models/app_config.rb, app/models/application_record.rb, app/models/equipment_model.rb, config/environments/production.rb
Resolves #1708
- Add `ApplicationRecord.paperclip_url` to override custom defaults when using S3
- Made `AppConfig` inherit from `ApplicationRecord` instead of `ActiveRecord::Base`
=> [1708] Permit the use of AWS regions other than us-east-1

.rubocop.yml, CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/announcements_controller.rb, app/controllers/blackouts_controller.rb, app/controllers/requirements_controller.rb, app/models/category.rb, app/models/checkin_procedure.rb, app/models/checkout_procedure.rb, app/models/concerns/soft_deletable.rb, app/models/equipment_item.rb, app/models/equipment_model.rb, config/application.rb, spec/concerns/soft_deletable_spec.rb, spec/features/eq_model_deactivation_spec.rb, spec/models/category_spec.rb, spec/models/checkin_procedure_spec.rb, spec/models/checkout_procedure_spec.rb, spec/models/equipment_item_spec.rb, spec/models/equipment_model_spec.rb
Resolves #1715
- Remove gem permanent_records
- Add SoftDeletable concern that allows for any model that has a
`deleted_at` attribute to implement a form of soft deletion by writing
to that attribute instead of removing the record by default.
- Add feature spec for deactivation of equipment model
=> [1715] Fix deactivation / activation by implement our own soft deletion

CHANGELOG.md, app/helpers/users_helper.rb, app/views/layouts/_flash_alerts.html.erb, app/views/terms_of_service/_user_accepted.html.erb, spec/helpers/users_helper_spec.rb
I think this got left off when doing the security scrub of `html_safe`. Changed the `filter_html` to `true`by default to scrub any weird tags users may have put in the DB.
We may want to think about scrubbing user inputs before persisting data in the future.
=> Fix flashes escaping html and TOS display bug

CHANGELOG.md, lib/csv_import.rb
Resolves #1748
Allows admins to upload a user import CSV file with only the usernames
populated in order to change their roles in bulk (e.g. to ban them).
Previously this would only work if the CSV file contained all required
user attributes.
~~Blocked on #1736 and #1751.~~
=> [1748] Allow for bulk user role updates with only usernames
